// Code generated by pkg/version/generate; DO NOT EDIT.
// Generated at: 2026-02-07T22:22:28Z

package main

import "git.sr.ht/~jakintosh/command-go/pkg/version"

var VersionInfo = version.Info{
	Version:   "1a6f4c6-dirty",
	Commit:    "1a6f4c671fe84b43e35b9f62b5885785b7b01dd8",
	BuildDate: "2026-02-07T22:22:28Z",
}
