// Code generated by pkg/version/generate; DO NOT EDIT.
// Generated at: 2026-02-07T19:50:05Z

package main

import "git.sr.ht/~jakintosh/command-go/pkg/version"

var VersionInfo = version.Info{
	Version:   "5fa9fcc-dirty",
	Commit:    "5fa9fcca43b593f6d0a9a31d722501eac8860a3a",
	BuildDate: "2026-02-07T19:50:05Z",
}
